import { describe, expect, it } from "vitest"
import type { ApiArtifact } from "../../lib/api/types"
import { translate, type MessageKey } from "../../i18n"
import { artifactLabel, formatSize, mayDelete, sourceLabel } from "./display"

const t = (key: MessageKey, vars?: Record<string, string | number>) => translate("en", key, vars)

function artifact(overrides: Partial<ApiArtifact> = {}): ApiArtifact {
  return {
    id: "gsyt7at6cjfr33d73mta",
    space_id: "t_1",
    filename: "report.md",
    media_type: "text/markdown",
    size_bytes: 100,
    sha256: "abc",
    created_by_type: "user",
    created_by_id: "u_1",
    source_type: "user_upload",
    preview: "inline",
    created_at: "2026-09-01T00:00:00Z",
    ...overrides,
  }
}

describe("artifactLabel", () => {
  it("prefers the title the producer gave", () => {
    expect(artifactLabel(artifact({ title: "Q3 findings" }))).toBe("Q3 findings")
  })

  // A title of spaces is a title nobody can read; the filename always says
  // something, so a blank-ish title must not win over it.
  it.each(["", "   "])("falls back to the filename for title %j", (title) => {
    expect(artifactLabel(artifact({ title }))).toBe("report.md")
  })
})

describe("formatSize", () => {
  it.each([
    [0, "0 B"],
    [999, "999 B"],
    [1024, "1.0 KB"],
    [10 * 1024, "10 KB"],
    [1024 * 1024, "1.0 MB"],
    [5 * 1024 * 1024 * 1024, "5.0 GB"],
    // Nothing above GB: a larger file keeps counting in GB rather than
    // running off the end of the unit list.
    [4096 * 1024 * 1024 * 1024, "4096 GB"],
  ])("renders %i bytes as %s", (bytes, expected) => {
    expect(formatSize(bytes)).toBe(expected)
  })
})

describe("sourceLabel", () => {
  it.each([
    ["task_run", "Produced by a run"],
    ["agent", "Saved by an agent"],
    ["system", "Generated by BuildMax"],
    ["user_upload", "Uploaded"],
  ])("describes %s", (sourceType, expected) => {
    expect(sourceLabel(artifact({ source_type: sourceType }), t)).toBe(expected)
  })
})

/**
 * The server is the authority; this only decides whether to offer the button.
 * Both directions matter: a button that 403s wastes a click, and a hidden one
 * makes a member think they cannot clean up their own upload.
 */
describe("mayDelete", () => {
  it.each(["admin", "owner"])("lets an %s remove anything the space holds", (role) => {
    const agentMade = artifact({ created_by_type: "agent", created_by_id: "ag_9" })
    expect(mayDelete(agentMade, "u_1", role)).toBe(true)
  })

  it("lets a member remove their own upload", () => {
    expect(mayDelete(artifact(), "u_1", "member")).toBe(true)
  })

  it("does not let a member remove someone else's upload", () => {
    expect(mayDelete(artifact({ created_by_id: "u_2" }), "u_1", "member")).toBe(false)
  })

  // The case a member actually hits: agents are the main producer, and a
  // member cannot delete what one published.
  it("does not let a member remove what an agent published", () => {
    const agentMade = artifact({ created_by_type: "agent", created_by_id: "u_1" })
    expect(mayDelete(agentMade, "u_1", "member")).toBe(false)
  })

  // Roles arrive from a separate request, so both are briefly unknown. An
  // unknown user offers nothing; an unknown role still offers someone their
  // own upload, which is what the server would allow at any role.
  it("offers nothing until the user is known", () => {
    expect(mayDelete(artifact(), undefined, null)).toBe(false)
  })

  it("offers a member their own upload before the role has loaded", () => {
    expect(mayDelete(artifact(), "u_1", null)).toBe(true)
  })
})
